### ISSUE TITLE
Upgrade dependencies 

### ISSUE THREAD

**Issue by llei4** [SpoonX/SxBlog#27]
Hello,

Please, could you upgrade dependencies of "zf-commons/zfc-user-doctrine-orm"?

I can't use "zf-commons/zfc-user-doctrine-orm": "^1.0" in my composer.json because yours is using "zf-commons/zfc-user-doctrine-orm": "0.*", so I get the following error:

Can only install one of: zf-commons/zfc-user-doctrine-orm[0.1.x-dev, 1.0.1].

Thanks.

**Comment by RWOverdijk** [comment]
Submit a PR :)

**Comment by llei4** [comment]
Done :)

**Comment by RWOverdijk** [comment]
Thanks! :)
